[package]
name = "notifications"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diesel = { version = "2.2.0", features = ["postgres"], path = "../../../diesel" }
pq-sys = { workspace = true, features = ["bundled"] }
openssl-sys = { workspace = true, features = ["vendored"] }
dotenvy = "0.15.6"

[[bin]]
name = "notifications"
doc = false
